#!/usr/bin/env sh

echo "----------------------------------------------"
echo "| Writing all kiln logs to ./kiln.logs.gz... |"
echo "----------------------------------------------"
zgrep --no-filename -E "(INFO|WARN|ERROR) (oven|kiln-controller|gevent)" /var/log/* 2>/dev/null|strings|sort|uniq|gzip > kiln.logs.gz

ls -la kiln.logs.gz

# for me to use to grab stats
#gzip -cd kiln.logs.gz|grep "INFO oven: temp="|sed 's/^.*\(....-..-.. ..:..:..,... INFO oven: temp=\)/\1/'|sort|uniq
