#!/usr/bin/env sh

echo "----------------------------------------------"
echo "| Writing all kiln logs to ./kiln.logs.gz... |"
echo "----------------------------------------------"
zcat -f /var/log/* 2>/dev/null|strings|grep -E "(INFO|WARN|ERROR) (oven|kiln-controller|gevent)"|sort|uniq|gzip > kiln.logs.gz

ls -la kiln.logs.gz

# for me to use to grab stats
#gzip -cd kiln.logs.gz|grep "INFO oven: temp="|sed 's/^.*\(....-..-.. ..:..:..,... INFO oven: temp=\)/\1/'|sort|uniq
